language: java
bundler_args: --retry 1

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/ru/r2cloud/

script:
  - mvn test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
